server:
  port: 10000

spring:
  application:
    name: wen-eureka-server #指定服务名称
  # profiles:
  #  active: dev  #要进行集群配置的话 在a机器使用dev 在b机器使用uat

eureka:
  instance:
    hostname: localhost #指定主机地址
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html #控制台查看swagger api文档
  client:
    register-with-eureka: false #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    fetch-registry: false #此客户端是否获取eureka服务器注册表上的注册信息，默认为true
  server:
    enable-self-preservation: false #关闭保护模式