eureka:
  client:
    register-with-eureka: true # 注册到eureka注册中心
    fetch-registry: true # 获取注册示例列表
    service-url:
      defaultZone: http://localhost:10000/eureka/

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.163.com # smtp.163.com smtp.qq.com
    username: yxwenqiyu@163.com # 邮箱
    password: YPLMVLDMGUWTOMGG # 邮箱授权码